name: Desmond Fung 
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
paginate: 5
remote_theme: jekyll-theme-lanyon
description: 'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
plugins:
  - jekyll-paginate

#Site settings
title: Welcome to my website!
email: dfung2@wisc.edu
url: https://ddhangdd.github.io
baseurl: ''
cv: https://github.com/ddhangdd/ddhangdd.github.io/raw/master/hw08.pdf
author.name: Desmond Fung
