name: Desmond Fung 
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
paginate: 5
remote_theme: jekyll-theme-lanyon
description: 'My facebook Account <a href="https://www.facebook.com/desmond.fung.1" target="_blank">Facebook</a>
plugins:
  - jekyll-paginate

#Site settings
title: Welcome to my website!
email: dfung2@wisc.edu
url: https://ddhangdd.github.io
baseurl: ''
cv: https://github.com/ddhangdd/ddhangdd.github.io/raw/master/hw08.pdf
author.name: Desmond Fung
