name: Desmond Fung 
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

theme: jekyll-theme-cayman

#Site settings
title: Desmond website
email: dfung2@wisc.edu
url: https://ddhangdd.github.io/
cv: https://github.com/ddhangdd/ddhangdd.github.io/raw/master/hw08.pdf
author.name: Desmond Fung
